language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master

before_script:
  - composer selfupdate
  - composer install --dev --prefer-source;
  - php -n ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false