language: php

php:
  - 5.3
  - 5.4
  - 5.5

branches:
  only:
    - master

before_script:
  - composer selfupdate
  - composer install --prefer-dist --dev
  - cd tests

notifications:
  email: false